misc:
  seed: 12345
  print_freq: 10
  num_workers: 8
  devices: [0, 1]
  model_dir: experiments

dataset:
  nmodal: 2
  src_dir: data/processed/12m
  dst_dir: data/processed/6m

model:
  patch_size: [64, 64, 64]
  latent_dim: 256

train:
  lr_gen: 1.0e-4
  lr_dis: 1.0e-4
  niter: 250
  epoch: 100
  batch_size: 2
  aug:
    rot: 30
    scale: [0.7, 1.4]

test:
  patch_overlap: [32, 32, 32]
  batch_size: 2
  out_dir: data/syn