misc:
  seed: 12345
  print_freq: 10
  num_workers: 8
  devices: [0, 1]
  model_dir: experiments

dataset:
  nmodal: 2
  nclass: 3
  src_dir: data/processed/12m
  syn_dir: data/syn/12m

model:
  midc: 64
  stages: 4
  patch_size: [128, 128, 64]

train:
  lr: 1.0e-2
  momentum: 0.9
  weight_decay: 1.0e-4
  niter: 250
  nepoch: 50
  batch_size: 4